name: smart_executer_example
description: Example app demonstrating the Smart Executer package.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  smart_executer:
    path: ../
  dio: ^5.4.0
  # Genius Systems packages integration
  smart_pagination: ^2.5.0
  super_dialog: ^0.3.0+2
  tooltip_card: ^2.6.2
  # Routing
  go_router: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  go_router_builder: ^4.1.3

flutter:
  uses-material-design: true
